apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: elasticsearch
  namespace: {{.Release.Namespace}}
spec:
  serviceName: elasticsearch
  replicas: 1
  selector:
    matchLabels:
      app: elasticsearch
  template:
    metadata:
      labels:
        app: elasticsearch
    spec:
      containers:
        - name: elasticsearch
          image: "{{.Values.efk.elasticsearch.image.name}}:{{.Values.efk.elasticsearch.image.tag}}"
          resources:
            limits:
              cpu: {{.Values.efk.elasticsearch.resources.limits.cpu}}
            requests:
              cpu: {{.Values.efk.elasticsearch.resources.requests.cpu}}
          ports:
            - containerPort: 9200
              protocol: TCP
            - containerPort: 9300
              protocol: TCP
          volumeMounts:
            - name: elastic-data
              mountPath: /usr/share/elasticsearch/data
          env:
            - name: cluster.name
              value: kubernetes-logging
            - name: node.name
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: discovery.seed_hosts
              value: "elasticsearch-0.elasticsearch"
            - name: cluster.initial_master_nodes
              value: "elasticsearch-0"
            - name: EA_JAVA_OPTS
              value: "{{.Values.efk.elasticsearch.javaOps}}"
      initContainers:
        - name: fix-permissions
          image: busybox
          command: ["sh", "-c", "chown -R 1000:1000 /usr/share/elasticsearch/data"]
          securityContext:
            privileged: true
          volumeMounts:
            - name: elastic-data
              mountPath: /usr/share/elasticsearch/data
        - name: increase-vm-max-map
          image: busybox
          command: ["sysctl", "-w", "vm.max_map_count=262144"]
          securityContext:
            privileged: true
  volumeClaimTemplates:
    - metadata:
        name: elastic-data
        labels:
          app: elasticsearch
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: elasticsearch-premium
        resources:
          requests:
            storage: {{.Values.efk.elasticsearch.data.diskQuota}}