apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: elasticsearch-premium
provisioner: kubernetes.io/azure-file
allowVolumeExpansion: true
reclaimPolicy: Delete
volumeBindingMode: Immediate
parameters:
  skuName: Premium_LRS