---
kind: Ingress
apiVersion: extensions/v1beta1
metadata:
  name: kibana
  namespace: {{.Release.Namespace}}
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  tls:
    - hosts:
      - kibana-{{.Values.global.spaceName}}.{{ .Values.dns.domain }}
      secretName: "{{ .Values.dns.sslCert }}"
  rules:
    - host: kibana-{{.Values.global.spaceName}}.{{ .Values.dns.domain }}
      http:
        paths:
        - path: "/"
          backend:
            serviceName: kibana
            servicePort: 443