---
kind: Ingress
apiVersion: extensions/v1beta1
metadata:
  name: kibana
  namespace: {{.Release.Namespace}}
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
    nginx.ingress.kubernetes.io/rewrite-target: "/"
    nginx.ingress.kubernetes.io/configuration-snippet: |
      rewrite (?i)/kibana/(.*) /$1 break;
      rewrite (?i)/kibana$ / break;
spec:
  tls:
    - hosts:
      - kibana-{{.Values.global.spaceName}}.{{ .Values.dns.domain }}
      secretName: "{{ .Values.dns.sslCert }}"
  rules:
    - host: kibana-{{.Values.global.spaceName}}.{{ .Values.dns.domain }}
      http:
        paths:
        - path: "/"
          backend:
            serviceName: kibana
            servicePort: 5601