apiVersion: v1
kind: Service
metadata:
  name: kibana
  namespace: {{.Release.Namespace}}
  labels:
    app: kibana
spec:
  selector:
    app: kibana
  ports:
    - name: http
      port: 80
      targetPort: 4180
      protocol: TCP