acr:
  name: oneesdevacr
dns:
  domain: "aks.run"
  sslCert: sslcert-aks-run
  resourceGroup: sace-bedrock-lab
  image:
    name: "external-dns"
    tag: 720306
  useAdditionalDnsZone: false
  additionalZone:
    name: external-dns-old
    configSecretName: external-dns-old-config-file
    txtOwnerId: onees-int-disco-east-us
    dnsZoneResourceGroup: dev.avalanch.es
    domainFilter: dev.avalanch.es
aks:
  clusterName: sace-bedrock-lab
  location: westus2
imagePullSecrets: acr-auth