name: "fabrikate-prometheus-operator"
type: static
path: "./manifests"
hooks:
  before-install:
    - echo 'installing prometheus-operator'
  after-install:
    - echo 'installed prometheus-operator'
subcomponents:
  - name: "prometheus-operator"
    type: helm
    source: "https://github.com/helm/charts"
    method: "git"
    path: "stable/prometheus-operator"
    version: "faa7218217e328a53f0a709c53f2f81b50b2d039"
