config:
  installIstioServices: false # Setup VirtualServices to work with Istio
  flexvol:
    image:
      name: mcr.microsoft.com/k8s/flexvolume/keyvault-flexvolume
      tag: v0.0.15
namespace: kv
injectNamespace: true # Namespace all templates
