apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{.Values.name}}
  namespace: {{.Release.Namespace}}
spec:
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: {{.Values.name}}
    spec:
      serviceAccountName: external-dns
      containers:
        - name: external-dns
          image: "{{.Values.acr.name}}.azurecr.io/{{.Values.dns.image.name}}:{{.Values.dns.image.tag}}"
          resources:
            requests:
              cpu: "50m"
              memory: "25Mi"
            limits:
              cpu: "100m"
              memory: "100Mi"
          args:
            - --source=service
            - --source=ingress
            - --domain-filter={{.Values.domainFilter}}
            - --provider=azure
            - --azure-resource-group={{.Values.dnsZoneResourceGroup}}
            - --txt-owner-id={{.Values.txtOwnerId}}
            - --log-level=debug
            - --policy=sync
          volumeMounts:
          - name: azure-config-file
            mountPath: /etc/kubernetes
            readOnly: true

      imagePullSecrets:
        - name: {{.Values.imagePullSecrets}}

      volumes:
        - name: azure-config-file
          secret:
            secretName: {{.Values.configSecretName}}