{
 "title": "Weave Flux",
 "description": "Dashboard for Weave Flux",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "instance",
    "label": "Instance",
    "query": "label_values(flux_daemon_job_duration_seconds_bucket, job)"
   }
  ]
 },
 "panels": [
  {
   "title": "Duration of cache requests, in seconds.",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(rate(flux_cache_request_duration_seconds_sum{job=\"$instance\"}[5m])) by (method)",
     "legendFormat": "{{method}}"
    }
   ]
  },
  {
   "title": "Duration of remote image metadata requests",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(rate(flux_client_fetch_duration_seconds_sum{job=\"$instance\"}[5m])) by (kind)",
     "legendFormat": "{{kind}}"
    }
   ]
  },
  {
   "title": "Duration of job execution, in seconds",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "flux_daemon_job_duration_seconds_sum{job=\"$instance\"}",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Duration of time spent in the job queue before execution",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "flux_daemon_queue_duration_seconds_sum{job=~\"$instance\"}",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Count of jobs waiting in the queue to be run",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "flux_daemon_queue_length_count", "legendFormat": "jobs" }
   ]
  },
  {
   "title": "Duration of git-to-cluster synchronisation",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(rate(flux_daemon_sync_duration_seconds_sum{job=\"$instance\"}[5m])) by (success)",
     "legendFormat": "success: {{success}}"
    }
   ]
  },
  {
   "title": "Duration of image metadata requests (from cache)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(rate(flux_registry_fetch_duration_seconds_sum{job=\"$instance\"}[5m]))",
     "legendFormat": "Registry fetch"
    }
   ]
  },
  {
   "title": "Duration in seconds of the current connection to fluxsvc",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(rate(flux_fluxd_connection_duration_seconds{job=\"$instance\"}[5m]))",
     "legendFormat": "Connection duration"
    }
   ]
  }
 ]
}